/**
 * symbolIndex.ts — address <-> symbol, and function extents, from generated artifacts.
 *
 * Two directions are needed by different consumers and they are not the same
 * map: resolving `$gp + displacement` back to a name wants address -> symbol
 * with interior references attributed to their base label, while resolving a
 * relocation wants symbol -> address exactly.
 *
 * Every input is generated by the split pipeline, so nothing here is specific
 * to one game.
 */

import { existsSync, readFileSync, readdirSync, statSync } from "fs";
import { join } from "path";
import { ROOT } from "./psxExeInfo.js";

export interface FunctionSpan {
  name: string;
  vram: number;
  rom: number;
  size: number;
  /** `c` once splat expects a C implementation, `asm` while it does not. */
  kind: "c" | "asm";
}

export interface SplatSubsegment {
  rom: number;
  vram: number;
  /** splat's type token: `c`, `asm`, `.rodata`, `o`, `bin`, … */
  type: string;
  name: string | null;
  /** Distance to the next subsegment of any kind. */
  size: number;
}

/**
 * Every subsegment in configs/splat.yaml, with its address resolved.
 *
 * splat annotates most function subsegments with `# 0xVRAM name`, but not all
 * of them — a subsegment it wrote without that comment is still a real
 * subsegment, and a reader that requires the comment silently loses those
 * functions. The enclosing segment's `start`/`vram` pair is enough to place any
 * subsegment, so the comment is used when present and derived otherwise.
 */
export function loadSubsegments(): SplatSubsegment[] {
  const yaml = readFileSync(join(ROOT, "configs/splat.yaml"), "utf-8");
  const partial: Array<Omit<SplatSubsegment, "size">> = [];
  let segmentStart: number | null = null;
  let segmentVram: number | null = null;
  let pendingStart: number | null = null;

  for (const line of yaml.split("\n")) {
    const start = line.match(/^\s*start:\s*(0x[0-9A-Fa-f]+|\d+)\s*$/);
    if (start) {
      pendingStart = Number(start[1]);
      continue;
    }
    const vram = line.match(/^\s*vram:\s*(0x[0-9A-Fa-f]+|\d+)\s*$/);
    if (vram) {
      segmentVram = Number(vram[1]);
      segmentStart = pendingStart;
      continue;
    }

    const entry = line.match(/^\s*-\s*\[([^\]]*)\]\s*(?:#\s*(0x[0-9A-Fa-f]+)\s+(\S+))?/);
    if (!entry) continue;
    const fields = entry[1].split(",").map((field) => field.trim());
    if (!/^(0x[0-9A-Fa-f]+|\d+)$/.test(fields[0])) continue;
    const rom = Number(fields[0]);
    const derived = segmentStart !== null && segmentVram !== null
      ? segmentVram + (rom - segmentStart)
      : 0;
    partial.push({
      rom,
      vram: entry[2] ? Number(entry[2]) : derived,
      type: fields[1] ?? "",
      name: fields[2] || entry[3] || null,
    });
  }

  const offsets = [...new Set(partial.map((entry) => entry.rom))].sort((a, b) => a - b);
  return partial.map((entry) => {
    const index = offsets.indexOf(entry.rom);
    const next = (index >= 0 ? offsets[index + 1] : undefined) ?? entry.rom;
    return { ...entry, size: next - entry.rom };
  });
}

/** Function extents from configs/splat.yaml. */
export function loadFunctionSpans(): FunctionSpan[] {
  const spans: FunctionSpan[] = [];
  for (const entry of loadSubsegments()) {
    if (entry.type !== "c" && entry.type !== "asm") continue;
    if (!entry.name) continue;
    spans.push({ name: entry.name, vram: entry.vram, rom: entry.rom, size: entry.size, kind: entry.type });
  }
  return spans;
}

/** Data sections that occupy payload bytes, so a ROM offset places them. */
const LOADED_DATA_SECTIONS = new Set([".rodata", ".rdata", ".data", ".sdata"]);

/**
 * Data subsegments splat assigns to one function, e.g.
 * `- [0x808, .rodata, func_80011370]` — the only sound source for the original
 * base address of a jump table the compiler emits into the object.
 *
 * `.bss`/`.sbss` subsegments are deliberately excluded: they occupy no payload
 * bytes, so their ROM offset does not place them, and a derived address would
 * be a guess.
 */
export function loadFunctionDataSubsegments(functionName: string): Map<string, number> {
  const result = new Map<string, number>();
  for (const entry of loadSubsegments()) {
    if (entry.name !== functionName) continue;
    if (!LOADED_DATA_SECTIONS.has(entry.type)) continue;
    result.set(entry.type, entry.vram);
  }
  return result;
}

/** Every `.s` file splat generates, so data labels can be indexed by address. */
function collectAsmFiles(directory: string, accumulator: string[] = []): string[] {
  if (!existsSync(directory)) return accumulator;
  for (const entry of readdirSync(directory)) {
    const path = join(directory, entry);
    if (statSync(path).isDirectory()) collectAsmFiles(path, accumulator);
    else if (entry.endsWith(".s")) accumulator.push(path);
  }
  return accumulator;
}

/** `NAME = 0xADDR;` tables the split pipeline generates or the project maintains. */
const ASSIGNMENT_FILES = [
  "configs/symbol_addrs.txt",
  "build/undefined_syms_auto.txt",
  "build/undefined_funcs_auto.txt",
  "build/dep_syms.txt",
  "build/lib_bss_syms.txt",
];

export interface SymbolIndex {
  /** Exact address -> symbol name. */
  byAddress: Map<number, string>;
  /** Ascending addresses, for resolving an interior reference to its base. */
  addresses: number[];
}

/**
 * Address -> symbol, from the generated artifacts that already carry it.
 *
 * `dlabel`/`glabel`/`jlabel` in splat's assembly are authoritative for
 * extracted data; the `NAME = 0xADDR;` tables cover symbols that have no
 * extracted bytes. Nothing here is specific to one game.
 */
export function loadSymbolIndex(): SymbolIndex {
  const byAddress = new Map<number, string>();

  for (const relative of ASSIGNMENT_FILES) {
    const file = join(ROOT, relative);
    if (!existsSync(file)) continue;
    for (const line of readFileSync(file, "utf-8").split("\n")) {
      const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+)/);
      if (match) byAddress.set(Number(match[2]), match[1]);
    }
  }

  /* Data labels win over the assignment tables: they are the extracted
   * definition, and splat regenerates them from the binary every split. */
  for (const file of collectAsmFiles(join(ROOT, "build/asm"))) {
    let pending: string | null = null;
    for (const line of readFileSync(file, "utf-8").split("\n")) {
      const label = line.match(/^\s*(?:dlabel|glabel|jlabel)\s+([A-Za-z_][A-Za-z0-9_]*)/);
      if (label) {
        pending = label[1];
        continue;
      }
      if (!pending) continue;
      const located = line.match(/\/\*\s*[0-9A-Fa-f]+\s+([0-9A-Fa-f]{8})\s/);
      if (located) {
        byAddress.set(Number(`0x${located[1]}`), pending);
        pending = null;
      }
    }
  }

  return { byAddress, addresses: [...byAddress.keys()].sort((a, b) => a - b) };
}

/** The symbol an address falls in: exact name, or base symbol plus offset. */
export function resolveAddress(index: SymbolIndex, address: number): { symbol: string; offset: number } | null {
  const exact = index.byAddress.get(address);
  if (exact) return { symbol: exact, offset: 0 };

  let low = 0;
  let high = index.addresses.length - 1;
  let base: number | undefined;
  while (low <= high) {
    const mid = (low + high) >> 1;
    const candidate = index.addresses[mid];
    if (candidate === undefined) break;
    if (candidate <= address) {
      base = candidate;
      low = mid + 1;
    } else high = mid - 1;
  }
  if (base === undefined) return null;
  const symbol = index.byAddress.get(base);
  return symbol === undefined ? null : { symbol, offset: address - base };
}

/**
 * The address splat encodes in a generated symbol name.
 *
 * splat names an otherwise anonymous symbol after its address, so the name
 * itself is a witness even when no table lists it. Only splat's own generated
 * prefixes are decoded — a hand-named symbol that happens to end in eight hex
 * digits is not an address, and guessing one would be exactly the confident
 * wrong answer this pipeline must never produce.
 */
export function addressEncodedInName(name: string): number | null {
  const match = name.match(/^(?:D|B|func|jtbl)_([0-9A-Fa-f]{8})$/);
  return match ? Number(`0x${match[1]}`) : null;
}

/**
 * `SYMBOL = 0xADDR;` assignments in the generated linker script.
 *
 * These are addresses the link defines rather than the binary carries — `_gp`
 * above all — so a relocation can name one even though no symbol table does.
 * They feed the name -> address direction only: they place no bytes, so
 * attributing an address back to one would shadow the real label there.
 */
function loadLinkerScriptSymbols(): Map<string, number> {
  const result = new Map<string, number>();
  const yaml = readFileSync(join(ROOT, "configs/splat.yaml"), "utf-8");
  const scriptPath = yaml.match(/ld_script_path:\s*(\S+)/)?.[1];
  if (!scriptPath) return result;
  const file = join(ROOT, scriptPath);
  if (!existsSync(file)) return result;
  for (const line of readFileSync(file, "utf-8").split("\n")) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+)\s*;/);
    if (match) result.set(match[1], Number(match[2]));
  }
  return result;
}

/**
 * Symbol -> address, exactly.
 *
 * The reverse of `loadSymbolIndex`, built from the same generated inputs plus
 * the linker script's own definitions. A name that no table covers falls back
 * to the address splat encoded in it, and is otherwise absent — never guessed.
 */
export function loadSymbolAddresses(): Map<string, number> {
  const byName = new Map<string, number>(loadLinkerScriptSymbols());

  for (const relative of ASSIGNMENT_FILES) {
    const file = join(ROOT, relative);
    if (!existsSync(file)) continue;
    for (const line of readFileSync(file, "utf-8").split("\n")) {
      const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+)/);
      if (match) byName.set(match[1], Number(match[2]));
    }
  }

  for (const file of collectAsmFiles(join(ROOT, "build/asm"))) {
    let pending: string | null = null;
    for (const line of readFileSync(file, "utf-8").split("\n")) {
      const label = line.match(/^\s*(?:dlabel|glabel|jlabel)\s+([A-Za-z_][A-Za-z0-9_]*)/);
      if (label) {
        pending = label[1];
        continue;
      }
      if (!pending) continue;
      const located = line.match(/\/\*\s*[0-9A-Fa-f]+\s+([0-9A-Fa-f]{8})\s/);
      if (located) {
        byName.set(pending, Number(`0x${located[1]}`));
        pending = null;
      }
    }
  }

  return byName;
}
