/**
 * analyzeStoreBlock.ts — data archaeology for store-dominated blocks
 *
 * When a function's mismatch is order-only inside a block of constant/pointer
 * stores, the cause is usually source statement order, and the right order is
 * the natural DATA order — not the emitted order. This tool mines the target
 * assembly for the evidence that decides it:
 *
 *   1. Store map: contiguous store runs (arrays) per region, ascending.
 *   2. Parallel arrays: adjacent equal-count runs (struct-of-arrays tables).
 *   3. Value relationships: pointer runs that are running sums of a parallel
 *      count run times an element size (pool-carving tables), common-divisor
 *      element-size candidates, repeated constants (one CSE web per value).
 *   4. Constant birth-order fingerprint: CSE materializes a shared constant at
 *      its FIRST use in source statement order, and that birth order survives
 *      scheduling even though store order does not. If the target's li order
 *      equals first-use order under ascending-offset stores, the original
 *      source wrote the block in natural ascending order.
 *
 * Usage: npx tsx tools/agent/analyzeStoreBlock.ts <func>
 *        npx tsx tools/agent/analyzeStoreBlock.ts <func> --target path/to.s
 *        npx tsx tools/agent/analyzeStoreBlock.ts <func> --candidate path/to.s
 *
 * The candidate comparison defaults to build/diffFunc/<func>.s when present
 * (regenerated by every diffFunc run). Symbolic tracking is linear (no CFG);
 * that is sufficient for initializer blocks, which are straight-line.
 */

import { existsSync, readFileSync, readdirSync } from "fs";
import { join } from "path";

const ROOT = new URL("../..", import.meta.url).pathname;

const NUM_REG = [
  "zero", "at", "v0", "v1", "a0", "a1", "a2", "a3",
  "t0", "t1", "t2", "t3", "t4", "t5", "t6", "t7",
  "s0", "s1", "s2", "s3", "s4", "s5", "s6", "s7",
  "t8", "t9", "k0", "k1", "gp", "sp", "fp", "ra",
];

type Val =
  | { kind: "sym"; sym: string; off: number }
  | { kind: "hi"; sym: string; off: number }
  | { kind: "const"; val: number }
  | null;

interface Store {
  idx: number;
  width: number;
  baseReg: string;
  base: Val;
  offset: number;
  value: Val;
}

interface LiEvent {
  idx: number;
  val: number;
}

function regName(r: string): string {
  const t = r.replace(/^\$/, "");
  if (/^\d+$/.test(t)) return NUM_REG[parseInt(t, 10)] ?? t;
  return t;
}

function parseImm(s: string): number | null {
  const m = s.trim().match(/^(-?)0x([0-9a-fA-F]+)$/) ?? s.trim().match(/^(-?)(\d+)$/);
  if (!m) return null;
  const v = m[0].includes("0x") ? parseInt(m[2], 16) : parseInt(m[2], 10);
  return m[1] === "-" ? -v : v;
}

/** Parse "%hi(SYM)" / "%lo(SYM + 0x60)" into { sym, off }. */
function parseReloc(s: string): { part: "hi" | "lo"; sym: string; off: number } | null {
  const m = s.trim().match(/^%(hi|lo)\(([^)]+)\)$/);
  if (!m) return null;
  const inner = m[2].split("+");
  const off = inner.length > 1 ? parseImm(inner[1]) ?? 0 : 0;
  return { part: m[1] as "hi" | "lo", sym: inner[0].trim(), off };
}

const STORE_WIDTH: Record<string, number> = { sw: 4, sh: 2, sb: 1, swl: 4, swr: 4 };
const LOADS = new Set(["lw", "lh", "lhu", "lb", "lbu", "lwl", "lwr"]);
const CALLER_SAVED = ["v0", "v1", "a0", "a1", "a2", "a3", "t0", "t1", "t2", "t3", "t4", "t5", "t6", "t7", "t8", "t9", "ra"];

/** Linear symbolic scan over (mnemonic, operands[]) rows. */
function scan(rows: { mn: string; ops: string[] }[]): { stores: Store[]; lis: LiEvent[] } {
  const regs = new Map<string, Val>();
  const stores: Store[] = [];
  const lis: LiEvent[] = [];
  const get = (r: string): Val => regs.get(r) ?? null;
  const set = (r: string, v: Val) => { if (r !== "zero") regs.set(r, v); };

  rows.forEach(({ mn, ops }, idx) => {
    if (mn in STORE_WIDTH) {
      const m = ops[1]?.match(/^(-?(?:0x[0-9a-fA-F]+|\d+))\((\$\w+)\)$/);
      if (m) {
        const baseReg = regName(m[2]);
        if (baseReg !== "sp") {
          stores.push({
            idx, width: STORE_WIDTH[mn], baseReg,
            base: get(baseReg), offset: parseImm(m[1]) ?? 0,
            value: get(regName(ops[0])),
          });
        }
      }
      return;
    }
    if (mn === "jal" || mn === "jalr") {
      for (const r of CALLER_SAVED) regs.set(r, null);
      return;
    }
    const rd = ops[0] ? regName(ops[0]) : "";
    switch (mn) {
      case "lui": {
        const rel = parseReloc(ops[1] ?? "");
        if (rel) set(rd, { kind: "hi", sym: rel.sym, off: rel.off });
        else {
          const imm = parseImm(ops[1] ?? "");
          set(rd, imm !== null ? { kind: "const", val: imm << 16 } : null);
        }
        break;
      }
      case "addiu": case "addi": case "ori": {
        const rs = get(regName(ops[1] ?? ""));
        const rsName = regName(ops[1] ?? "");
        const rel = parseReloc(ops[2] ?? "");
        const imm = parseImm(ops[2] ?? "");
        if (rel && rs && rs.kind === "hi" && rs.sym === rel.sym) {
          set(rd, { kind: "sym", sym: rel.sym, off: rs.off + rel.off });
        } else if (imm !== null && rsName === "zero") {
          set(rd, { kind: "const", val: mn === "ori" ? imm >>> 0 : imm });
          lis.push({ idx, val: mn === "ori" ? imm >>> 0 : imm });
        } else if (imm !== null && rs && rs.kind === "sym") {
          set(rd, { kind: "sym", sym: rs.sym, off: rs.off + imm });
        } else if (imm !== null && rs && rs.kind === "const") {
          set(rd, { kind: "const", val: mn === "ori" ? (rs.val | imm) : rs.val + imm });
        } else set(rd, null);
        break;
      }
      case "li": { /* GCC candidate output uses the li macro directly */
        const imm = parseImm(ops[1] ?? "");
        set(rd, imm !== null ? { kind: "const", val: imm } : null);
        if (imm !== null) lis.push({ idx, val: imm });
        break;
      }
      case "addu": case "add": {
        const a = get(regName(ops[1] ?? "")), b = ops[2] ? get(regName(ops[2])) : null;
        const imm = ops[2] ? parseImm(ops[2]) : null;
        if (imm !== null && a) {
          /* GCC macro form: addu rd, rs, imm */
          if (a.kind === "sym") set(rd, { kind: "sym", sym: a.sym, off: a.off + imm });
          else if (a.kind === "const") set(rd, { kind: "const", val: a.val + imm });
          else set(rd, null);
        } else if (a?.kind === "sym" && b?.kind === "const") set(rd, { kind: "sym", sym: a.sym, off: a.off + b.val });
        else if (b?.kind === "sym" && a?.kind === "const") set(rd, { kind: "sym", sym: b.sym, off: b.off + a.val });
        else if (a?.kind === "const" && b?.kind === "const") set(rd, { kind: "const", val: a.val + b.val });
        else set(rd, null);
        break;
      }
      case "move": set(rd, get(regName(ops[1] ?? ""))); break;
      default:
        /* Anything else that writes a GPR destination invalidates it. */
        if (LOADS.has(mn) || /^(sub|subu|and|andi|xor|xori|nor|slt|slti|sltiu|sltu|sll|srl|sra|sllv|srlv|srav|mflo|mfhi|negu|seb|seh)$/.test(mn)) {
          set(rd, null);
        }
        break;
    }
  });
  return { stores, lis };
}

/** Parse splat/objdump-style target asm ("/* addr vram bytes *​/ mn ops"). */
function parseTargetAsm(path: string): { mn: string; ops: string[] }[] {
  const rows: { mn: string; ops: string[] }[] = [];
  for (const line of readFileSync(path, "utf-8").split("\n")) {
    const m = line.match(/^\s*\/\* [0-9A-Fa-f]+ [0-9A-Fa-f]+ [0-9A-Fa-f]+ \*\/\s+(\S+)\s*(.*)$/);
    if (!m) continue;
    rows.push({ mn: m[1].toLowerCase(), ops: m[2].split(",").map((s) => s.trim()).filter(Boolean) });
  }
  return rows;
}

/** Parse GCC-emitted candidate asm (tabs, numeric registers, # comments). */
function parseGccAsm(path: string): { mn: string; ops: string[] }[] {
  const rows: { mn: string; ops: string[] }[] = [];
  for (const line of readFileSync(path, "utf-8").split("\n")) {
    const noComment = line.split("#")[0];
    const m = noComment.match(/^\s+([a-z][a-z0-9.]*)\s+(.*)$/);
    if (!m || m[1].startsWith(".")) continue;
    rows.push({ mn: m[1].toLowerCase(), ops: m[2].split(",").map((s) => s.trim()).filter(Boolean) });
  }
  return rows;
}

function resolveTargetAsm(name: string): string {
  const primary = join(ROOT, `build/asm/nonmatchings/${name}/${name}.s`);
  if (existsSync(primary)) return primary;
  const dir = join(ROOT, `build/asm/nonmatchings/${name}`);
  if (existsSync(dir)) {
    const files = readdirSync(dir).filter((f) => f.endsWith(".s"));
    if (files.length === 1) return join(dir, files[0]);
  }
  return "";
}

function fmtVal(v: Val): string {
  if (!v) return "?";
  if (v.kind === "const") return `0x${v.val.toString(16).toUpperCase()}`;
  if (v.kind === "sym") return v.off ? `${v.sym}+0x${v.off.toString(16).toUpperCase()}` : v.sym;
  return `%hi(${v.sym})`;
}

function firstUseOrder(values: number[]): number[] {
  const seen: number[] = [];
  for (const v of values) if (!seen.includes(v)) seen.push(v);
  return seen;
}

function gcd(a: number, b: number): number { return b ? gcd(b, a % b) : a; }

interface Run { key: string; width: number; start: number; stores: Store[] }

function main() {
  const args = process.argv.slice(2);
  const name = args.find((a) => !a.startsWith("--")) ?? "";
  const flag = (f: string) => { const i = args.indexOf(f); return i >= 0 ? args[i + 1] : undefined; };
  if (!name) { console.error("usage: analyzeStoreBlock.ts <func> [--target file.s] [--candidate file.s]"); process.exit(1); }

  const targetPath = flag("--target") ?? resolveTargetAsm(name);
  if (!targetPath || !existsSync(targetPath)) {
    console.error(`No target asm found for ${name} (looked in build/asm/nonmatchings/). Pass --target.`);
    process.exit(1);
  }
  const { stores, lis } = scan(parseTargetAsm(targetPath));
  console.log(`target: ${targetPath.replace(ROOT, "")}`);
  console.log(`stores tracked: ${stores.length} (sp-relative excluded)\n`);
  if (stores.length < 4) { console.log("Fewer than 4 non-stack stores — no store block to analyze."); return; }

  /* ---- 1. store runs per region, ascending ---- */
  const regionOf = (s: Store) =>
    s.base?.kind === "sym" ? s.base.sym : `reg:${s.baseReg}`;
  const absOff = (s: Store) => (s.base?.kind === "sym" ? s.base.off : 0) + s.offset;

  const byRegion = new Map<string, Store[]>();
  for (const s of stores) {
    const k = `${regionOf(s)}|${s.width}`;
    (byRegion.get(k) ?? byRegion.set(k, []).get(k)!).push(s);
  }
  const runs: Run[] = [];
  for (const [k, list] of byRegion) {
    const sorted = [...list].sort((a, b) => absOff(a) - absOff(b));
    let run: Store[] = [];
    for (const s of sorted) {
      if (run.length && absOff(s) !== absOff(run[run.length - 1]) + s.width) {
        if (run.length >= 2) runs.push({ key: k.split("|")[0], width: run[0].width, start: absOff(run[0]), stores: run });
        run = [];
      }
      run.push(s);
    }
    if (run.length >= 2) runs.push({ key: k.split("|")[0], width: run[0].width, start: absOff(run[0]), stores: run });
  }
  runs.sort((a, b) => a.key.localeCompare(b.key) || a.start - b.start);

  console.log("== Store runs (contiguous, ascending) ==");
  for (const r of runs) {
    const w = r.width === 4 ? "word" : r.width === 2 ? "half" : "byte";
    console.log(`  ${r.key} +0x${r.start.toString(16).toUpperCase()}: ${r.stores.length} x ${w}`);
    console.log(`    values: ${r.stores.map((s) => fmtVal(s.value)).join(", ")}`);
  }

  /* ---- 2. parallel arrays ---- */
  console.log("\n== Parallel-array candidates ==");
  let foundParallel = false;
  for (const a of runs) for (const b of runs) {
    if (a === b || a.key !== b.key) continue;
    if (a.start + a.stores.length * a.width === b.start && a.stores.length === b.stores.length) {
      foundParallel = true;
      console.log(`  ${a.key}: ${a.stores.length}-entry table — ${a.width}-byte run @+0x${a.start.toString(16).toUpperCase()} adjacent to ${b.width}-byte run @+0x${b.start.toString(16).toUpperCase()}`);
    }
  }
  if (!foundParallel) console.log("  none");

  /* ---- 3. value relationships ---- */
  console.log("\n== Value relationships ==");
  for (const p of runs) {
    const vals = p.stores.map((s) => s.value);
    if (!vals.every((v) => v?.kind === "sym" && v.sym === (vals[0] as any).sym)) continue;
    const offs = vals.map((v: any) => v.off as number);
    const deltas = offs.slice(1).map((o, i) => o - offs[i]);
    if (!deltas.length || deltas.some((d) => d <= 0)) continue;
    const g = deltas.reduce(gcd);
    console.log(`  pointer run ${p.key}+0x${p.start.toString(16).toUpperCase()} into ${(vals[0] as any).sym}: deltas gcd = 0x${g.toString(16).toUpperCase()} (element-size candidate)`);
    for (const c of runs) {
      if (c === p || c.stores.length !== p.stores.length) continue;
      const cv = c.stores.map((s) => s.value);
      if (!cv.every((v) => v?.kind === "const" && v.val > 0)) continue;
      const counts = cv.map((v: any) => v.val as number);
      if (deltas[0] % counts[0] !== 0) continue;
      const E = deltas[0] / counts[0];
      if (deltas.every((d, i) => d === counts[i] * E)) {
        const total = counts.reduce((x, y) => x + y, 0);
        console.log(`    POOL-CARVING TABLE: delta[i] == count[i] * 0x${E.toString(16).toUpperCase()} against count run @+0x${c.start.toString(16).toUpperCase()} (all ${deltas.length} deltas verified)`);
        console.log(`    ${total} elements of size 0x${E.toString(16).toUpperCase()} total; entries are (pointer, count) pairs — natural source order is ascending, entries written together.`);
      }
    }
  }
  const constStores = stores.filter((s) => s.value?.kind === "const")
    .sort((a, b) => regionOf(a).localeCompare(regionOf(b)) || absOff(a) - absOff(b));
  const constVals = constStores.map((s) => (s.value as any).val as number);
  const repeats = [...new Set(constVals.filter((v, i) => constVals.indexOf(v) !== i))];
  if (repeats.length) {
    console.log(`  repeated stored constants (one CSE web / one li each): ${repeats.map((v) => `0x${v.toString(16).toUpperCase()}`).join(", ")}`);
  }

  /* ---- 4. constant birth-order fingerprint ---- */
  console.log("\n== Constant birth-order fingerprint ==");
  const storedSet = new Set(constVals);
  const targetBirth = firstUseOrder(lis.map((l) => l.val).filter((v) => storedSet.has(v)));
  const naturalFirstUse = firstUseOrder(constVals);
  const show = (a: number[]) => a.map((v) => `0x${v.toString(16).toUpperCase()}`).join(", ");
  console.log(`  target li birth order:            ${show(targetBirth)}`);
  console.log(`  first-use under ascending order:  ${show(naturalFirstUse)}`);
  if (targetBirth.length && targetBirth.join() === naturalFirstUse.join()) {
    if (targetBirth.length >= 4) {
      console.log("  MATCH — the original source almost certainly wrote these stores in");
      console.log("  natural ascending offset order. Write the source that way and let the");
      console.log("  scheduler do the shuffling; do NOT copy the emitted store order.");
    } else {
      console.log("  match, but too few distinct constants for a strong verdict.");
    }
  } else if (targetBirth.length) {
    console.log("  MISMATCH — ascending order alone does not explain the birth order.");
    console.log("  Look for an entry order implied by the data (paired/interleaved,");
    console.log("  grouped by table), and re-check against its first-use order.");
  }

  /* candidate comparison */
  const candPath = flag("--candidate") ?? join(ROOT, `build/diffFunc/${name}.s`);
  if (existsSync(candPath)) {
    const cand = scan(parseGccAsm(candPath));
    const candBirth = firstUseOrder(cand.lis.map((l) => l.val).filter((v) => storedSet.has(v)));
    console.log(`\n  candidate (${candPath.replace(ROOT, "")}):`);
    console.log(`  candidate li birth order:         ${show(candBirth)}`);
    if (candBirth.join() === targetBirth.join()) {
      console.log("  candidate birth order matches the target.");
    } else {
      const i = candBirth.findIndex((v, j) => v !== targetBirth[j]);
      console.log(`  DIVERGES from target at position ${i} — the candidate's statement order`);
      console.log("  poisons constant birth order. Fix source statement order first;");
      console.log("  scheduler forensics cannot recover from an upstream order error.");
    }
  }
}

main();
