/**
 * contextExport.ts — Extract function signatures from decompiled C files into the m2c context
 *
 * Stage 4 of the decompilation pipeline. After a function is byte-matched and cleaned up,
 * this tool extracts its signature and adds it to the m2c context so that future
 * m2c runs and LLM agents have type context.
 *
 * Two files are generated, and m2c must be given them in this order:
 *   include/sdk_types.h  — definitions of every type the signatures name
 *   include/functions.h  — the signatures themselves
 *
 * Both are m2c context only. Nothing #includes them, and they carry no
 * preprocessor directives, because m2c parses its context as plain C with no
 * preprocessor.
 *
 * Usage:
 *   npx tsx tools/agent/contextExport.ts func_80011F08          # extract from src/func_80011F08.c
 *   npx tsx tools/agent/contextExport.ts --all                   # extract from all decompiled src/*.c
 *   npx tsx tools/agent/contextExport.ts func_80011F08 --dry-run # show what would be added
 */

import { execFileSync } from "child_process";
import { readFileSync, writeFileSync, existsSync, readdirSync, rmSync } from "fs";
import { join } from "path";
import {
  extractPrototypesFromSource,
  extractSignaturesFromSource,
  harvestTypedefs,
  renderSdkTypesHeader,
  resolveTypes,
  typeNamesIn,
  type ExtractedSignature,
  type Resolution,
} from "./sdkTypes.js";

const ROOT = new URL("../..", import.meta.url).pathname;

const SDK_TYPES_HEADER = "include/sdk_types.h";
const FUNCTIONS_HEADER = "include/functions.h";

interface ExportResult {
  signatures: string[];
  skipped: boolean;
  reason?: string;
}

/**
 * Extract the function definitions a decompiled C file publishes.
 */
export function extractSignaturePairs(cFilePath: string): ExtractedSignature[] {
  if (!existsSync(cFilePath)) return [];

  const source = readFileSync(cFilePath, "utf-8");

  // Skip stubs that still use INCLUDE_ASM
  if (source.includes("INCLUDE_ASM(")) return [];

  return extractSignaturesFromSource(source);
}

/**
 * Extract function signatures from a decompiled C file.
 */
export function extractSignatures(cFilePath: string): string[] {
  return extractSignaturePairs(cFilePath).map((s) => s.signature);
}

/**
 * Read the current include/functions.h and return a map of funcName -> signature.
 */
function readExistingHeader(headerPath: string): Map<string, string> {
  const map = new Map<string, string>();
  if (!existsSync(headerPath)) return map;

  for (const { name, signature } of extractPrototypesFromSource(readFileSync(headerPath, "utf-8"))) {
    map.set(name, signature);
  }
  return map;
}

/* ------------------------------------------------------------------ */
/* Context generation                                                  */
/* ------------------------------------------------------------------ */

/**
 * Resolve the type definitions the signatures require, and report which
 * signature pulled in any type that could not be resolved.
 */
export function resolveContextTypes(
  rootDir: string,
  signatures: Map<string, string>,
): { resolution: Resolution; defs: Map<string, string>; referencedBy: Map<string, string[]> } {
  const defs = harvestTypedefs(rootDir);

  const referencedBy = new Map<string, string[]>();
  for (const sig of signatures.values()) {
    for (const name of typeNamesIn(sig)) {
      const users = referencedBy.get(name);
      if (users) users.push(sig);
      else referencedBy.set(name, [sig]);
    }
  }

  return { resolution: resolveTypes(referencedBy.keys(), defs), defs, referencedBy };
}

/** Render include/functions.h: signatures only, sorted by name. */
function renderFunctionsHeader(signatures: Map<string, string>): string {
  const sorted = [...signatures.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  return [
    "/* Auto-generated by tools/agent/contextExport.ts — do not edit manually */",
    "/* m2c context only. Types live in include/sdk_types.h, which must be",
    " * passed to m2c before this file. */",
    "",
    ...sorted.map(([, sig]) => sig),
    "",
  ].join("\n");
}

/**
 * Ask m2c to parse the generated context, in the order consumers use it.
 *
 * The pair is verified together: sdk_types.h parses in isolation whether or
 * not functions.h does, so a per-file check would pass on exactly the
 * configuration that is broken.
 */
export function verifyContextParses(
  rootDir: string,
): { ok: boolean; skipped?: string; diagnostic?: string } {
  const asmRoot = join(rootDir, "build/asm/nonmatchings");
  if (!existsSync(asmRoot)) {
    return { ok: true, skipped: "build/asm/nonmatchings is absent (gitignored); cannot verify" };
  }
  const dirs = readdirSync(asmRoot).sort();
  let probe: { fn: string; sFile: string } | undefined;
  for (const dir of dirs) {
    const candidate = join(asmRoot, dir, `${dir}.s`);
    if (existsSync(candidate)) {
      probe = { fn: dir, sFile: candidate };
      break;
    }
  }
  if (!probe) return { ok: true, skipped: "no .s file available to verify against" };

  const args = [
    "tools/vendor/m2c/m2c.py",
    "--target", "mipsel-gcc-c",
    /* Parse fresh rather than trusting the on-disk .m2c cache: the point of
     * the gate is to check what was just written. */
    "--no-cache",
    "-f", probe.fn,
  ];
  const globalsCtx = join(rootDir, "build/m2c_globals.ctx");
  if (existsSync(globalsCtx)) args.push("--context", "build/m2c_globals.ctx");
  args.push("--context", SDK_TYPES_HEADER, "--context", FUNCTIONS_HEADER, probe.sFile);

  let output: string;
  try {
    output = execFileSync("python3", args, { cwd: rootDir, encoding: "utf-8", stdio: ["ignore", "pipe", "pipe"] });
  } catch (e: any) {
    output = `${e.stdout ?? ""}${e.stderr ?? ""}`;
  }

  /* Only a context parse failure is this gate's business. m2c can fail on a
   * given function for unrelated reasons without the context being at fault. */
  if (output.includes("Syntax error when parsing C context")) {
    return { ok: false, diagnostic: output.trim() };
  }
  return { ok: true };
}

/**
 * Write the m2c context pair, then prove it parses before letting it stand.
 *
 * The context is shared by every function, so an unparseable one disables the
 * tool project-wide. On failure both files are restored and the error is
 * raised: this must never return having left a context its consumer rejects.
 */
export function writeContext(rootDir: string, signatures: Map<string, string>): void {
  const sdkPath = join(rootDir, SDK_TYPES_HEADER);
  const funcsPath = join(rootDir, FUNCTIONS_HEADER);

  const { resolution, defs, referencedBy } = resolveContextTypes(rootDir, signatures);

  for (const name of resolution.unresolved) {
    const users = referencedBy.get(name) ?? [];
    console.warn(
      `warning: type '${name}' is referenced by a signature but defined nowhere. ` +
      `Emitting an opaque placeholder — its layout is a guess, so m2c output ` +
      `touching this type will be wrong.`,
    );
    for (const sig of users.slice(0, 3)) console.warn(`         referenced by: ${sig}`);
    if (users.length > 3) console.warn(`         ...and ${users.length - 3} more`);
  }

  const previous = new Map<string, string | null>([
    [sdkPath, existsSync(sdkPath) ? readFileSync(sdkPath, "utf-8") : null],
    [funcsPath, existsSync(funcsPath) ? readFileSync(funcsPath, "utf-8") : null],
  ]);

  writeFileSync(sdkPath, renderSdkTypesHeader(resolution, defs));
  writeFileSync(funcsPath, renderFunctionsHeader(signatures));

  const check = verifyContextParses(rootDir);
  if (check.skipped) {
    console.warn(`warning: context self-check skipped — ${check.skipped}`);
    return;
  }
  if (!check.ok) {
    for (const [path, content] of previous) {
      if (content === null) rmSync(path, { force: true });
      else writeFileSync(path, content);
    }
    throw new Error(
      `Generated m2c context does not parse; previous context restored.\n\n${check.diagnostic}`,
    );
  }
}

/**
 * Export context for a single function. Returns extracted signatures.
 * This is the entry point used by the orchestrator.
 */
export function exportContext(funcName: string, rootDir: string = ROOT): ExportResult {
  const cFile = join(rootDir, "src", `${funcName}.c`);

  if (!existsSync(cFile)) {
    return { signatures: [], skipped: true, reason: "file not found" };
  }

  const pairs = extractSignaturePairs(cFile);
  if (pairs.length === 0) {
    return { signatures: [], skipped: true, reason: "no function definitions (stub?)" };
  }
  const sigs = pairs.map((p) => p.signature);

  /* A matched caller may carry its own local prototype for this function
   * (period style: per-file declarations, often with all-s32 parameter
   * lists that the caller's byte match depends on). Publishing a
   * conflicting prototype in functions.h would break those TUs, so skip
   * and report instead of writing. */
  const srcDirGuard = join(rootDir, "src");
  const conflicting = readdirSync(srcDirGuard)
    .filter((f) => f.endsWith(".c") && f !== `${funcName}.c`)
    .filter((f) =>
      extractPrototypesFromSource(readFileSync(join(srcDirGuard, f), "utf-8"))
        .some((p) => p.name === funcName));
  if (conflicting.length > 0) {
    return {
      signatures: sigs,
      skipped: true,
      reason: `local prototype(s) exist in ${conflicting.join(", ")}; not publishing to functions.h (reconcile manually if desired)`,
    };
  }

  const existing = readExistingHeader(join(rootDir, FUNCTIONS_HEADER));
  for (const { name, signature } of pairs) existing.set(name, signature);

  writeContext(rootDir, existing);
  return { signatures: sigs, skipped: false };
}

/**
 * Collect the signatures published by every decompiled (non-stub) file in src/.
 */
function collectAllSignatures(rootDir: string): { signatures: Map<string, string>; exported: string[]; skipped: string[] } {
  const srcDir = join(rootDir, "src");
  const files = readdirSync(srcDir).filter((f) => f.endsWith(".c"));
  const signatures = readExistingHeader(join(rootDir, FUNCTIONS_HEADER));
  const exported: string[] = [];
  const skipped: string[] = [];

  for (const file of files) {
    const funcName = file.replace(/\.c$/, "");
    const pairs = extractSignaturePairs(join(srcDir, file));

    if (pairs.length === 0) {
      skipped.push(funcName);
      continue;
    }

    for (const { name, signature } of pairs) signatures.set(name, signature);
    exported.push(funcName);
  }

  return { signatures, exported, skipped };
}

/**
 * Export context for all decompiled (non-stub) C files in src/.
 */
export function exportAll(rootDir: string = ROOT): { exported: string[]; skipped: string[] } {
  const srcDir = join(rootDir, "src");
  if (!existsSync(srcDir)) return { exported: [], skipped: [] };

  const { signatures, exported, skipped } = collectAllSignatures(rootDir);

  if (exported.length > 0) {
    writeContext(rootDir, signatures);
  }

  return { exported, skipped };
}

// --- CLI ---

if (process.argv[1]?.endsWith("contextExport.ts")) {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const all = args.includes("--all");
  const funcName = args.find((a) => !a.startsWith("--"));

  if (!all && !funcName) {
    console.error("Usage: npx tsx tools/agent/contextExport.ts <func_name> [--dry-run]");
    console.error("       npx tsx tools/agent/contextExport.ts --all [--dry-run]");
    process.exit(1);
  }

  try {
    if (all) {
      if (dryRun) {
        const { signatures } = collectAllSignatures(ROOT);
        const { resolution, defs } = resolveContextTypes(ROOT, signatures);
        console.log(renderSdkTypesHeader(resolution, defs));
        console.log(renderFunctionsHeader(signatures));
        console.log(
          `\n${signatures.size} signature(s), ${resolution.ordered.length} type(s) resolved, ` +
          `${resolution.unresolved.length} unresolved (dry run, nothing written)`,
        );
      } else {
        const result = exportAll();
        console.log(`Exported ${result.exported.length} function(s), skipped ${result.skipped.length} stub(s)`);
        if (result.exported.length > 0) {
          console.log(`Updated ${SDK_TYPES_HEADER} and ${FUNCTIONS_HEADER}`);
        }
      }
    } else {
      const cFile = join(ROOT, "src", `${funcName}.c`);
      const sigs = extractSignatures(cFile);

      if (sigs.length === 0) {
        console.log(`No function definitions found in src/${funcName}.c (stub or missing)`);
        process.exit(0);
      }

      for (const sig of sigs) {
        console.log(`  ${sig}`);
      }

      if (dryRun) {
        console.log(`(dry run, nothing written)`);
      } else {
        const result = exportContext(funcName!);
        if (!result.skipped) {
          console.log(`Updated ${SDK_TYPES_HEADER} and ${FUNCTIONS_HEADER}`);
        } else if (result.reason) {
          console.log(`Skipped: ${result.reason}`);
        }
      }
    }
  } catch (e: any) {
    console.error(e.message);
    process.exit(1);
  }
}
