/* Auto-generated by tools/agent/contextExport.ts — do not edit manually */
/* m2c context only. Types live in include/sdk_types.h, which must be
 * passed to m2c before this file. */

void ovl_10_func_800B9060(void);
void ovl_10_func_800B92AC(void);
int ovl_10_func_800B92D0(int arg0);
int ovl_10_func_800B9458(int arg0);
int ovl_10_func_800B94A4(int arg0);
int ovl_10_func_800B956C(int arg0);
int ovl_10_func_800B95A4(int arg0);
int ovl_10_func_800B9AA8(s32 arg0, s32 arg1);
int ovl_10_func_800B9D24(int arg0, int arg1);
s32 ovl_10_func_800BA11C(s32 arg0, s32 arg1);
int ovl_10_func_800BA2A0(int arg0, int arg1);
s32 ovl_10_func_800BA394(s32 arg0, s32 arg1);
int ovl_10_func_800BAB10(int arg0, int arg1);
int ovl_10_func_800BACBC(s32 arg0, s32 arg1);
int ovl_10_func_800BADA4(int arg0, int arg1);
int ovl_10_func_800BB264(int arg0, int arg1);
s32 ovl_10_func_800BB728(s32 arg0);
