/* Auto-generated by tools/agent/contextExport.ts — do not edit manually */
/* m2c context only. Types live in include/sdk_types.h, which must be
 * passed to m2c before this file. */

void ovl_17_func_800B7E38(void);
void ovl_17_func_800B9DB8(s16 arg0);
void ovl_17_func_800B9DE0(s16 arg0);
void ovl_17_func_800B9E0C(s16 arg0);
s32 ovl_17_func_800B9F78(s16 arg0);
s32 ovl_17_func_800BAFAC(Recon_ovl_17_func_800BAFAC_A0View *arg0, s32 arg1, s32 arg2, s32 arg3);
s32 ovl_17_func_800BB020(Recon_ovl_17_func_800BB020_A0View *arg0, s32 arg1, s32 arg2, s32 arg3);
s32 ovl_17_func_800BB094(Recon_ovl_17_func_800BB094_A0View *arg0, s32 arg1, s32 arg2, s32 arg3);
