/* Auto-generated by tools/agent/contextExport.ts — do not edit manually */
/* m2c context only. Types live in include/sdk_types.h, which must be
 * passed to m2c before this file. */

void ovl_19_func_800B7ED8(void);
void ovl_19_func_800B843C(void);
void ovl_19_func_800B847C(void);
void ovl_19_func_800B8544(void);
s32 ovl_19_func_800B85F4(void);
void ovl_19_func_800B8E88(void);
void ovl_19_func_800B93B0(void);
void ovl_19_func_800B942C(void);
void ovl_19_func_800B9DC8(void);
s32 ovl_19_func_800B9DD0(Recon_ovl_19_func_800B9DD0_A0View *arg0, s32 arg1, s32 arg2, s32 arg3);
void ovl_19_func_800BA054(Recon_ovl_19_func_800BA054_A0View *arg0, s32 arg1, s32 arg2, s32 arg3);
s32 ovl_19_func_800BA25C(void);
s32 ovl_19_func_800BA2D4(void);
s32 ovl_19_func_800BA544(s32 arg0);
void ovl_19_func_800BA564(M2C_2b0e4444e645_ReconA0View *arg0, M2C_2b0e4444e645_ReconA1View *arg1);
s32 ovl_19_func_800BA5B4(M2C_3ad8e07a3b9c_ReconA0View *arg0, M2C_3ad8e07a3b9c_ReconA1View *arg1);
void ovl_19_func_800BA628(M2C_190b52b5a3be_ReconA0View *arg0, M2C_190b52b5a3be_ReconA1View *arg1);
s32 ovl_19_func_800BA73C(Ovl19Func800BA73CArg *arg0);
s32 ovl_19_func_800BA750(M2C_d030f1db9199_Recon800BA750A0View *arg0);
void ovl_19_func_800BAC40(Ovl19Func800BAC40Arg *arg0, s32 arg1, s32 arg2, s32 arg3);
void ovl_19_func_800BAC50(Ovl19Func800BAC40Arg *arg0, s32 arg1, s32 arg2);
void ovl_19_func_800BAC5C(void);
void ovl_19_func_800BAC7C(void);
void ovl_19_func_800BAD50(void);
s32 ovl_19_func_800BADAC(s16 arg0);
void ovl_19_func_800BB08C(s32 arg0, s32 arg1);
void ovl_19_func_800BB318(void);
void ovl_19_func_800BB470(void);
void ovl_19_func_800BB4D4(void);
void ovl_19_func_800BB848(void);
void ovl_19_func_800BBCCC(void);
void ovl_19_func_800BBD14(s16 arg0);
