/* Auto-generated by tools/agent/contextExport.ts — do not edit manually */
/* m2c context only. Types live in include/sdk_types.h, which must be
 * passed to m2c before this file. */

void ovl_08_func_800B8014(void);
void ovl_08_func_800B8054(void);
void ovl_08_func_800B80FC(void);
void ovl_08_func_800B8134(void);
void ovl_08_func_800B8400(void);
