/* Auto-generated by tools/agent/contextExport.ts — do not edit manually */
/* m2c context only. Types live in include/sdk_types.h, which must be
 * passed to m2c before this file. */

void ovl_19_func_800B942C(void);
void ovl_19_func_800B9DC8(void);
s32 ovl_19_func_800B9DD0(Recon_ovl_19_func_800B9DD0_A0View *arg0, s32 arg1, s32 arg2, s32 arg3);
void ovl_19_func_800BA054(Recon_ovl_19_func_800BA054_A0View *arg0, s32 arg1, s32 arg2, s32 arg3);
s32 ovl_19_func_800BA544(s32 arg0);
void ovl_19_func_800BA564(ReconA0View *arg0, ReconA1View *arg1);
void ovl_19_func_800BA628(ReconA0View *arg0, ReconA1View *arg1);
s32 ovl_19_func_800BA73C(Ovl19Func800BA73CArg *arg0);
void ovl_19_func_800BAC40(Ovl19Func800BAC40Arg *arg0, s32 arg1, s32 arg2, s32 arg3);
void ovl_19_func_800BAC50(Ovl19Func800BAC40Arg *arg0, s32 arg1, s32 arg2);
void ovl_19_func_800BAC5C(void);
void ovl_19_func_800BAC7C(void);
