/* Auto-generated by tools/agent/contextExport.ts — do not edit manually */
/* m2c context only. Types live in include/sdk_types.h, which must be
 * passed to m2c before this file. */

void ovl_11_func_800BCF20(void);
void ovl_11_func_800BD160(void);
void ovl_11_func_800BD5A0(void);
void ovl_11_func_800BFEF8(void);
void ovl_11_func_800DBFE4(void);
void ovl_11_func_800F1F40(void);
void ovl_11_func_800F4A50(void);
void ovl_11_func_800F6630(void);
void ovl_11_func_800F6638(void);
void ovl_11_func_800F6640(void);
void ovl_11_func_800F6670(void);
void ovl_11_func_80104898(void);
void ovl_11_func_80104A80(void);
void ovl_11_func_80104A88(void);
