/* Auto-generated by tools/agent/contextExport.ts — do not edit manually */
/* m2c context only. Types live in include/sdk_types.h, which must be
 * passed to m2c before this file. */

void ovl_25_func_800B93BC(void);
void ovl_25_func_800B93E4(void);
s32 ovl_25_func_800B9758(ReconA0View *arg0);
