name: ovl_27
sha1: 429e3b9eb31def8a2493d4028c28a2a81e048f1a
options:
  platform: psx
  compiler: GCC
  basename: ovl_27
  base_path: ../..
  build_path: build
  ld_script_path: build/ovl_27/ovl_27.ld
  target_path: extracted/overlays/ovl_27.bin
  asm_path: build/ovl_27/asm
  src_path: src/overlays/ovl_27
  asset_path: assets
  symbol_addrs_path:
    - configs/symbols/ovl_27.txt
    - build/engine_syms.txt
  undefined_funcs_auto_path: build/ovl_27/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/ovl_27/undefined_syms_auto.txt
  find_file_boundaries: false
  disasm_unknown: true
  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  extensions_path: tools/vendor/splat_ext
  subalign: 4

segments:
  - name: ovl_27
    type: code
    start: 0x0
    vram: 0x800B7E20
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0xCC, c, ovl_27_func_800B7EEC]
      - [0x10C, c, ovl_27_func_800B7F2C]
      - [0x15C, c, ovl_27_func_800B7F7C]
      - [0x1C8, c, ovl_27_func_800B7FE8]
      - [0x290, c, ovl_27_func_800B80B0]
      - [0x41C, c, ovl_27_func_800B823C]
      - [0x63C, c, ovl_27_func_800B845C]
      - [0xE4C, c, ovl_27_func_800B8C6C]
      - [0xE8C, c, ovl_27_func_800B8CAC]
      - [0xF08, c, ovl_27_func_800B8D28]
      - [0x1008, c, ovl_27_func_800B8E28]
      - [0x103C, c, ovl_27_func_800B8E5C]
      - [0x1080, c, ovl_27_func_800B8EA0]
      - [0x10D8, c, ovl_27_func_800B8EF8]
      - [0x1138, c, ovl_27_func_800B8F58]
      - [0x11A8, c, ovl_27_func_800B8FC8]
      - [0x1244, c, ovl_27_func_800B9064]
      - [0x12BC, c, ovl_27_func_800B90DC]
      - [0x1304, c, ovl_27_func_800B9124]
      - [0x1404, c, ovl_27_func_800B9224]
      - [0x146C, c, ovl_27_func_800B928C]
      - [0x14C4, c, ovl_27_func_800B92E4]
      - [0x1504, c, ovl_27_func_800B9324]
      - [0x1548, c, ovl_27_func_800B9368]
      - [0x1594, c, ovl_27_func_800B93B4]
      - [0x15E0, c, ovl_27_func_800B9400]
      - [0x162C, c, ovl_27_func_800B944C]
      - [0x1B6C, c, ovl_27_func_800B998C]
      - [0x1C6C, c, ovl_27_func_800B9A8C]
      - [0x1D78, c, ovl_27_func_800B9B98]
      - [0x1E64, c, ovl_27_func_800B9C84]
      - [0x1E94, c, ovl_27_func_800B9CB4]
      - [0x1F9C, c, ovl_27_func_800B9DBC]
      - [0x20CC, c, ovl_27_func_800B9EEC]
      - [0x21D4, c, ovl_27_func_800B9FF4]
      - [0x2288, c, ovl_27_func_800BA0A8]
      - [0x22CC, c, ovl_27_func_800BA0EC]
      - [0x2310, c, ovl_27_func_800BA130]
      - [0x23AC, c, ovl_27_func_800BA1CC]
      - [0x2410, c, ovl_27_func_800BA230]
      - [0x26A4, c, ovl_27_func_800BA4C4]
      - [0x26F4, c, ovl_27_func_800BA514]
      - [0x2758, c, ovl_27_func_800BA578]
      - [0x279C, c, ovl_27_func_800BA5BC]
      - [0x2800, c, ovl_27_func_800BA620]
      - [0x2930, c, ovl_27_func_800BA750]
      - [0x2990, c, ovl_27_func_800BA7B0]
      - [0x29EC, c, ovl_27_func_800BA80C]
      - [0x29F4, c, ovl_27_func_800BA814]
      - [0x2AF4, c, ovl_27_func_800BA914]
      - [0x2C14, c, ovl_27_func_800BAA34]
      - [0x2DB4, c, ovl_27_func_800BABD4]
      - [0x2DF4, c, ovl_27_func_800BAC14]
      - [0x2E40, data]
  - [0xE000]
