/* Auto-generated by tools/contextExport.ts — do not edit manually */

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef signed char s8;
typedef signed short s16;
typedef signed int s32;

void func_80011EE8(void);
void func_80011F2C(s8 arg0);
u8 func_80011F38(void);
void func_80011F44(s32 arg0);
void func_80011F50(s32 arg0);
s32 func_800120BC(void);
s32 func_800129E8(void);
void func_80013438(s32 arg0);
void func_8001588C(void);
void func_80015894(void *arg0, s32 arg1);
s32 func_80017A64(void);
void func_80017B18(s32 arg0);
s32 func_8001B10C(void);
s32 func_8001DCA8(void);
void func_8001E158(void);
int func_8001FAB4(void);
s32 func_8001FB08(void);
void func_8001FCDC(void);
s32 func_8002040C(void);
s32 func_800207DC(void);
void func_800218BC(void);
void func_80021D70(void);
s32 func_80021D78(void);
void func_80021D80(void);
s32 func_80021D88(void);
void func_80021D90(void);
void func_80021D98(void);
void func_80021DA0(void);
void func_80022008(void);
void func_800226D8(s32 arg0);
