/* Auto-generated by tools/agent/contextExport.ts — do not edit manually */

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef signed char s8;
typedef signed short s16;
typedef signed int s32;

typedef struct {
    /* 0x00 */ char pad_00[0x02];
    /* 0x02 */ u16 field_2;     /* flags/status word */
    /* 0x04 */ s8 field_4;      /* state identifier */
    /* 0x05 */ s8 field_5;      /* sub-state or animation index */
    /* 0x06 */ s16 field_6;     /* timer or counter */
} ObjectState;

typedef struct {
    s32 field_0;
    s32 field_4;
} PairS32;

typedef struct {
    /* 0x00 */ s32 field_0x0;
    /* 0x04 */ s32 field_0x4;
    /* 0x08 */ s32 field_0x8;
    /* 0x0C */ s32 field_0xC;
    /* 0x10 */ s32 field_0x10;
    /* 0x14 */ s32 field_0x14;
    /* 0x18 */ s32 field_0x18;
    /* 0x1C */ s32 field_0x1C;
} SomeStruct;

typedef struct {
    /* 0x00 */ s8 field_0;
    /* 0x01 */ s8 field_1;
    /* 0x02 */ s8 field_2;
    /* 0x03 */ s8 field_3;
    /* 0x04 */ s8 field_4;
    /* 0x05 */ s8 field_5;
    /* 0x06 */ s8 field_6;
    /* 0x07 */ s8 field_7;
    /* 0x08 */ s16 field_8;
    /* 0x0A */ s16 field_A;
    /* 0x0C */ s8 field_C;
    /* 0x0D */ s8 field_D;
    /* 0x0E */ s8 field_E;
    /* 0x0F */ char pad_F;
    /* 0x10 */ s16 field_10;
    /* 0x12 */ s16 field_12;
    /* 0x14 */ s8 field_14;
    /* 0x15 */ s8 field_15;
    /* 0x16 */ s8 field_16;
    /* 0x17 */ char pad_17;
    /* 0x18 */ s16 field_18;
    /* 0x1A */ s16 field_1A;
    /* 0x1C */ s8 field_1C;
    /* 0x1D */ s8 field_1D;
    /* 0x1E */ s8 field_1E;
    /* 0x1F */ char pad_1F;
    /* 0x20 */ s16 field_20;
    /* 0x22 */ s16 field_22;
} Struct_800153BC;

typedef struct {
    /* 0x00 */ s8  field_0;
    /* 0x01 */ s8  field_1;
    /* 0x02 */ s8  field_2;
    /* 0x03 */ s8  field_3;
    /* 0x04 */ s8  field_4;
    /* 0x05 */ s8  field_5;
    /* 0x06 */ s8  field_6;
    /* 0x07 */ s8  field_7;
    /* 0x08 */ s16 field_8;
    /* 0x0A */ s16 field_A;
    /* 0x0C */ s16 field_C;
    /* 0x0E */ s16 field_E;
    /* 0x10 */ s16 field_10;
    /* 0x12 */ s16 field_12;
    /* 0x14 */ s16 field_14;
    /* 0x16 */ s16 field_16;
} Struct_800154CC;

typedef struct {
    s32 field_0;
    s32 field_4;
    s32 field_8;
} Struct_8001F39C;

typedef struct {
    /* 0x00 */ s32 field_0x00;
    /* 0x04 */ s32 field_0x04;
    /* 0x08 */ s32 field_0x08;
    /* 0x0C */ s32 field_0x0C;
    /* 0x10 */ s32 field_0x10;
    /* 0x14 */ s32 field_0x14;
    /* 0x18 */ char pad_18[0x08];
    /* 0x20 */ s32 field_0x20;
    /* 0x24 */ s32 field_0x24;
    /* 0x28 */ s32 field_0x28;
    /* 0x2C */ char pad_2C[0x08];
    /* 0x34 */ s16 field_0x34;
} Struct80013F90;

typedef struct {
    s32 x;
    s32 y;
    s32 z;
} Vec3;

void ClearPairS32(PairS32 *obj);
void ClearVal8005E2CC(void);
void ClearVal8005E2D4(void);
void ClearVal8005E2EC(void);
void ClearVal8005E49C(void);
void ClearVal8005E4B0(void);
void CopyVec3(Vec3 *dest, Vec3 *src);
void func_80011270(void);
void func_80011EE8(void);
s32 func_800129E8(void);
void func_800132B8(s32 arg0, s32 arg1, s32 arg2);
s32 func_800134B8(void);
void func_80013F90(Struct80013F90 *arg0);
s32 func_80014CB0(void);
void* func_800153BC(Struct_800153BC *arg0, s32 *arg1, s16 arg2, s16 arg3, s16 arg4, s16 arg5, s32 arg6, s32 arg7, s32 arg8, s32 arg9, s16 arg10);
void* func_800154CC(Struct_800154CC *arg0, s32 *arg1, s16 arg2, s16 arg3, s16 arg4, s16 arg5, s32 arg6, s16 arg7);
void func_80015840(ObjectState *obj, s8 arg1);
void func_8001585C(ObjectState *obj, s8 arg1);
void func_80015880(SomeStruct *arg0, s32 arg1, s32 arg2);
void func_8001588C(void);
void func_80015894(SomeStruct *arg0, s32 arg1);
void func_80017A38(s16 arg0, s16 arg1);
void func_80017A48(u32 arg0);
u32 func_80017A64(void);
void func_80017A70(u32 arg0);
void func_80017ACC(void);
void func_80017AE8(void);
s16 func_80017B30(void);
u16 func_80017C24(void);
u16 func_80017C30(void);
void func_80017C3C(s32 arg0);
u16 func_800195F4(void);
void func_80019600(void);
s32 func_80019E50(s32 arg0);
s32 func_8001A8D0(s32 arg0);
void func_8001ACA0(void);
void func_8001AF34(void);
s32 func_8001AF44(u32 arg0);
void func_8001B258(void);
void func_8001B4D0(s32 arg0, s32 arg1);
void func_8001B4E4(s32 arg0);
void func_8001B9F8(s32 arg0, s32 arg1, s32 arg2, s32 arg3);
void func_8001BA40(s32 arg0, s32 arg1, s32 arg2);
s32 func_8001D2D8(s16 arg0, s16 arg1, s16 arg2, s16 arg3);
s32 func_8001DCA8(void);
void func_8001E158(void);
s32 func_8001E7DC(s32 *arg0, s32 *arg1);
void func_8001F038(s32 arg0, s32 arg1, s32 arg2);
void func_8001F39C(Struct_8001F39C *arg0, Struct_8001F39C *arg1);
s32 func_8001FAB4(void);
s32 func_8001FB08(void);
void func_8001FBE4(s32 arg0, s32 arg1);
void func_8001FCDC(void);
void func_8001FCE4(void);
void func_8001FE00(s32 arg0);
void func_8001FF70(void);
s32 func_80020148(s32 arg0);
s32 func_80020174(s32 arg0, s32 arg1);
s32 func_8002040C(void);
s32 func_800207DC(void);
s32 func_80020E38(void);
void func_800215EC(s32 arg0, s32 arg1, s32 arg2);
s32 func_800217B0(s32 arg0, s32 arg1, s32 arg2, u8 *arg3);
s32 func_80021820(s32 arg0, s32 arg1);
void func_800218BC(void);
void func_80021D70(void);
s32 func_80021D78(void);
void func_80021D80(void);
s32 func_80021D88(void);
void func_80021D90(void);
void func_80021D98(void);
void func_80021DA0(void);
void func_80021FD0(void);
void func_80022008(void);
s32 func_8002261C(s32 arg0, s32 arg1);
s32 func_800226B0(void);
s16 func_80022AF0(void);
s32 func_80022F1C(s32 arg0);
void func_8002301C(void);
void func_80023100(void);
void func_80023A74(void);
s32 func_8002437C(s32 arg0, s32 arg1, s32 arg2);
s32 func_800244FC(s32 arg0, s32 arg1);
s32 func_80024578(s32 arg0, s32 arg1);
u16 func_800245C8(s32 arg0, s32 arg1);
u8 GetFlag8005E274(void);
s16 GetPairedTpage(s32 tpage);
s32 GetVal8005E29C(void);
s32 GetVal8005E2BC(void);
s32 GetVal8005E2CC(void);
s32 GetVal8005E2E4(void);
s32 GetVal8005E334(void);
s32 GetVal8005E394(void);
s32 GetVal8005E39C(void);
s32 GetVal8005E3B0(void);
s32 GetVal8005E3EC(void);
s32 GetVal8005E40C(void);
s32 GetVal8005E524(void);
s32 GetVal8005E544(void);
s32 GetVal8005E548(void);
s32 GetVal8005E55C(void);
s32 GetVal8005E5B4(void);
s32 GetVal8005E5B8(void);
s32 HasTriangleVertexXInBounds(s32 sxy0, s32 sxy1, s32 sxy2);
s32 pow_int(s32 arg0, s32 arg1);
u32 Rand(s32 arg0);
void SetFlag8005E274(u8 arg0);
void SetGfxClip(s32 arg0, s32 arg1);
void SetGfxOffset(s32 arg0, s32 arg1);
void SetVal8005E278(s32 arg0);
void SetVal8005E27C(s32 arg0);
void SetVal8005E280(s32 arg0);
void SetVal8005E29C(s32 arg0);
void SetVal8005E2BC(s32 arg0);
void SetVal8005E2D8(s32 arg0);
void SetVal8005E2E8(s32 arg0);
void SetVal8005E334(s32 arg0);
void SetVal8005E3EC(s32 arg0);
void SetVal8005E43C(s32 arg0);
void SetVal8005E51C(s32 arg0);
void SetVal8005E5C0(s32 arg0);
