/* Auto-generated by tools/contextExport.ts — do not edit manually */

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef signed char s8;
typedef signed short s16;
typedef signed int s32;

void func_80011EE8(void);
void func_8001588C(void);
void func_8001E158(void);
int func_8001FAB4(void);
void func_8001FCDC(void);
void func_800218BC(void);
void func_80021D70(void);
void func_80021D80(void);
void func_80021D90(void);
void func_80021D98(void);
void func_80021DA0(void);
