/* Auto-generated by tools/agent/contextExport.ts — do not edit manually */
/* m2c context only: type definitions for include/functions.h.
 * Must be passed to m2c *before* functions.h; see tools/agent/m2cFunc.ts. */

typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef signed char s8;
typedef signed short s16;
typedef signed int s32;

typedef struct {
    s16 field_0;
    s16 field_2;
    s16 field_4;
} CoordTri;

typedef unsigned long u_long;

typedef struct {
	u_long	tag;
	u_long	code[2];
} DR_MODE;

typedef struct {
    s32 field_0;
    s32 field_4;
    s32 field_8;
    s32 field_C;
    s32 field_10;
    s32 field_14;
} EAE4Query;

typedef struct {
    s16 field_00;
    u16 field_02;
} Group;

typedef unsigned char u_char;

typedef struct {
	u_long	tag;
	u_char	r0, g0, b0, code;
	short	x0, 	y0;
	short	x1,	y1;
} LINE_F2;

typedef struct {
    /* 0x00 */ char pad_00[0x02];
    /* 0x02 */ u16 field_2;     /* flags/status word */
    /* 0x04 */ s8 field_4;      /* state identifier */
    /* 0x05 */ s8 field_5;      /* sub-state or animation index */
    /* 0x06 */ s16 field_6;     /* timer or counter */
} ObjectState;

typedef unsigned short u_short;

typedef struct {
	u_long	tag;
	u_char	r0, g0, b0, code;
	short	x0, 	y0;
	u_char	u0, v0;	u_short	clut;
	short	x1,	y1;
	u_char	u1, v1;	u_short	tpage;
	short	x2,	y2;
	u_char	u2, v2;	u_short	pad1;
	short	x3,	y3;
	u_char	u3, v3;	u_short	pad2;
} POLY_FT4;

typedef struct {
    s32 field_0;
    s32 field_4;
} PairS32;

typedef struct {
    u_char b[4];
} ReadFlag;

typedef struct {
	u_long	tag;
	u_char	r0, g0, b0, code;
	short	x0, 	y0;
	u_char	u0, v0;	u_short	clut;
	short	w,	h;
} SPRT;

typedef struct {		/* short word type 3D vector */	
	short	vx, vy;
	short	vz, pad;
} SVECTOR;

typedef struct {
    /* 0x00 */ s32 field_0x0;
    /* 0x04 */ s32 field_0x4;
    /* 0x08 */ s32 field_0x8;
    /* 0x0C */ s32 field_0xC;
    /* 0x10 */ s32 field_0x10;
    /* 0x14 */ s32 field_0x14;
    /* 0x18 */ s32 field_0x18;
    /* 0x1C */ s32 field_0x1C;
} SomeStruct;

typedef struct {
    u16 field_00;
    u16 field_02;
    s16 field_04;
    s16 field_06;
} Vertex;

typedef struct {
    u16 field_00;
    u16 field_02;
    u16 field_04;
    u16 field_06;
    u16 field_08;
    u16 field_0A;
    u16 field_0C;
    u16 field_0E;
    s16 field_10;
    u16 field_12;
    u32 padding_14;
    u32 padding_18;
    Vertex *field_1C;
    Group *field_20;
    u8 *field_24;
    Group *field_28;
    u8 *field_2C;
    s32 field_30;
} SourceData;

typedef struct {
    /* 0x00 */ s16 unk0;
    /* 0x02 */ u16 unk2;
} SpriteRef;

typedef struct {
    /* 0x00 */ s16 unk0;
    /* 0x02 */ s16 unk2;
    /* 0x04 */ s16 unk4;
    /* 0x06 */ s16 unk6;
} SpriteTex;

typedef struct {
    /* 0x00 */ u16 unk0;
    /* 0x02 */ u16 unk2;
    /* 0x04 */ u8  unk4;
    /* 0x05 */ u8  unk5;
    /* 0x06 */ u16 unk6;
    /* 0x08 */ u8  pad8[0x14];
    /* 0x1C */ SpriteTex *unk1C;
    /* 0x20 */ SpriteRef *unk20;
    /* 0x24 */ u8 *unk24;
    /* 0x28 */ SpriteRef *unk28;
    /* 0x2C */ u8 *unk2C;
} SpriteSourceData;

typedef void (*SpriteCallback)(s32, SpriteSourceData *, s16, s32, s32);

typedef struct {
    /* 0x00 */ s32 tag;          /* magic value 0xE */
    /* 0x04 */ s32 field_4;
    /* 0x08 */ s32 field_8;
    /* 0x0C */ s32 field_C;
    /* 0x10 */ s32 offset_tex;   /* -> SpriteTex[] (cel/texture rectangles) */
    /* 0x14 */ s32 offset_ref;   /* -> SpriteRef[] (sprite entry indices) */
    /* 0x18 */ s32 offset_18;    /* -> entry data (SpriteEntry[]) */
    /* 0x1C */ s32 offset_anim;  /* -> SpriteRef[] (animation frame index table) */
    /* 0x20 */ s32 offset_frame; /* -> frame data (SpriteFrame[] / control bytes) */
} SpriteDataHeader;

typedef struct {
    /* 0x00 */ s32 field_0x00;
    /* 0x04 */ s32 field_0x04;
    /* 0x08 */ s32 field_0x08;
    /* 0x0C */ s32 field_0x0C;
    /* 0x10 */ s32 field_0x10;
    /* 0x14 */ s32 field_0x14;
    /* 0x18 */ s32 field_0x18;
    /* 0x1C */ s32 field_0x1C;
    /* 0x20 */ s32 field_0x20;
    /* 0x24 */ s32 field_0x24;
    /* 0x28 */ s32 field_0x28;
    /* 0x2C */ s32 field_0x2C;
    /* 0x30 */ s32 field_0x30;
    /* 0x34 */ s16 field_0x34;
    /* 0x36 */ u8 field_0x36;
    /* 0x37 */ u8 field_0x37;
} Struct80013F90;

typedef struct {
    /* 0x00 */ s8 field_0;
    /* 0x01 */ s8 field_1;
    /* 0x02 */ s8 field_2;
    /* 0x03 */ s8 field_3;
    /* 0x04 */ s8 field_4;
    /* 0x05 */ s8 field_5;
    /* 0x06 */ s8 field_6;
    /* 0x07 */ s8 field_7;
    /* 0x08 */ s16 field_8;
    /* 0x0A */ s16 field_A;
    /* 0x0C */ s8 field_C;
    /* 0x0D */ s8 field_D;
    /* 0x0E */ s8 field_E;
    /* 0x0F */ char pad_F;
    /* 0x10 */ s16 field_10;
    /* 0x12 */ s16 field_12;
    /* 0x14 */ s8 field_14;
    /* 0x15 */ s8 field_15;
    /* 0x16 */ s8 field_16;
    /* 0x17 */ char pad_17;
    /* 0x18 */ s16 field_18;
    /* 0x1A */ s16 field_1A;
    /* 0x1C */ s8 field_1C;
    /* 0x1D */ s8 field_1D;
    /* 0x1E */ s8 field_1E;
    /* 0x1F */ char pad_1F;
    /* 0x20 */ s16 field_20;
    /* 0x22 */ s16 field_22;
} Struct_800153BC;

typedef struct {
    /* 0x00 */ s8  field_0;
    /* 0x01 */ s8  field_1;
    /* 0x02 */ s8  field_2;
    /* 0x03 */ s8  field_3;
    /* 0x04 */ s8  field_4;
    /* 0x05 */ s8  field_5;
    /* 0x06 */ s8  field_6;
    /* 0x07 */ s8  field_7;
    /* 0x08 */ s16 field_8;
    /* 0x0A */ s16 field_A;
    /* 0x0C */ s16 field_C;
    /* 0x0E */ s16 field_E;
    /* 0x10 */ s16 field_10;
    /* 0x12 */ s16 field_12;
    /* 0x14 */ s16 field_14;
    /* 0x16 */ s16 field_16;
} Struct_800154CC;

typedef struct {
    s32 field_0;
    s32 field_4;
    s32 field_8;
} Struct_8001F39C;

typedef struct {
	u_long	tag;
	u_char	r0, g0, b0, code;
	short	x0, 	y0;
	short	w,	h;
} TILE;

typedef struct {
	u_long	tag;
	u_char	r0, g0, b0, code;
	short	x0, 	y0;
} TILE_1;

typedef struct {
    u8 b[4];
} TextFlag;

typedef struct {
    s32 x;
    s32 y;
    s32 z;
} Vec3;
