/**
 * classifyGlobals.ts — Generate include/globals.h with correct extern declarations
 *
 * GCC -G8 uses $gp-relative addressing for extern variables ≤ 8 bytes.
 * Symbols outside $gp's signed-16-bit range need absolute (lui + lo) addressing.
 * This tool generates declarations that make GCC choose the right mode.
 *
 * Symbols in GP range:  normal externs (GCC uses $gp-relative)
 * Symbols outside:      >8-byte array with __asm__ label + #define wrapper
 *                        (GCC uses absolute addressing, source code unchanged)
 *
 * Usage: npx tsx tools/classifyGlobals.ts [--write]
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from "fs";
import { join } from "path";

const ROOT = new URL("..", import.meta.url).pathname;
const writeMode = process.argv.includes("--write");

// --- Read gp_value from splat.yaml ---

function readGpValue(): number {
  const yaml = readFileSync(join(ROOT, "configs/splat.yaml"), "utf-8");
  const match = yaml.match(/gp_value:\s*(0x[0-9a-fA-F]+)/);
  if (!match) {
    console.error("Could not find gp_value in configs/splat.yaml");
    process.exit(1);
  }
  return parseInt(match[1], 16);
}

// --- Read symbols from undefined_syms_auto.txt ---

interface SymbolInfo {
  name: string;
  addr: number;
  inGpRange: boolean;
  cType: string; // inferred C type
}

function readSymbols(gpValue: number): SymbolInfo[] {
  const symsPath = join(ROOT, "build/undefined_syms_auto.txt");
  if (!existsSync(symsPath)) {
    console.error("build/undefined_syms_auto.txt not found. Run 'make split' first.");
    process.exit(1);
  }

  const gpLo = gpValue - 0x7ff0;
  const gpHi = gpValue + 0x7fef;

  const lines = readFileSync(symsPath, "utf-8").split("\n");
  const symbols: SymbolInfo[] = [];

  for (const line of lines) {
    const m = line.match(/^(\w+)\s*=\s*(0x[0-9a-fA-F]+)/);
    if (!m) continue;

    const name = m[1];
    const addr = parseInt(m[2], 16);

    // Only process D_ data symbols — skip functions and named symbols
    if (!name.startsWith("D_")) continue;

    const inGpRange = addr >= gpLo && addr <= gpHi;
    symbols.push({ name, addr, inGpRange, cType: "s32" }); // default type
  }

  return symbols;
}

// --- Infer types from asm access patterns ---

function inferTypes(symbols: SymbolInfo[]): void {
  const nonmatchingsDir = join(ROOT, "build/asm/nonmatchings");
  if (!existsSync(nonmatchingsDir)) return;

  // Build a quick lookup of all asm content
  const allAsm: string[] = [];
  for (const funcDir of readdirSync(nonmatchingsDir)) {
    const dirPath = join(nonmatchingsDir, funcDir);
    try {
      for (const f of readdirSync(dirPath)) {
        if (f.endsWith(".s")) {
          allAsm.push(readFileSync(join(dirPath, f), "utf-8"));
        }
      }
    } catch { /* skip non-directories */ }
  }
  const combined = allAsm.join("\n");

  // Map load/store instructions to C types
  // sb/lbu/lb → byte, sh/lhu/lh → short, sw/lw → word
  const typeMap: Record<string, string> = {
    sb: "s8", lb: "s8", lbu: "u8",
    sh: "s16", lh: "s16", lhu: "u16",
    sw: "s32", lw: "s32", lwu: "u32",
  };

  for (const sym of symbols) {
    // Look for %lo(SYM) or offset patterns with this symbol
    const accessPattern = new RegExp(
      `(\\w+)\\s+\\$\\w+,\\s*%lo\\(${sym.name}\\)`, "g"
    );

    let match: RegExpExecArray | null;
    while ((match = accessPattern.exec(combined)) !== null) {
      const instr = match[1].toLowerCase();
      if (typeMap[instr]) {
        sym.cType = typeMap[instr];
        break; // first access is good enough
      }
    }

    // Also check $gp-relative access patterns for in-range symbols
    // These won't have %lo() — they'll have numeric offsets from $gp
  }
}

// --- Generate header + linker aliases ---

function generateHeader(symbols: SymbolInfo[]): string {
  const lines: string[] = [
    "/* Generated by tools/classifyGlobals.ts — do not edit manually */",
    "#ifndef GLOBALS_H",
    "#define GLOBALS_H",
    "",
    "/* Requires common.h typedefs (s8, s16, s32, u8, u16, u32) */",
    "",
  ];

  const gpSyms = symbols.filter(s => s.inGpRange);
  const absSyms = symbols.filter(s => !s.inGpRange);

  if (gpSyms.length > 0) {
    lines.push("/* GP-relative symbols (within $gp ± 0x7FF0) */");
    for (const s of gpSyms) {
      lines.push(`extern ${s.cType} ${s.name};`);
    }
    lines.push("");
  }

  if (absSyms.length > 0) {
    lines.push("/* Absolute-addressed symbols (outside $gp range) */");
    lines.push("/* Declared as >8-byte arrays to force lui+lo addressing with -G8 */");
    lines.push("/* _far_ prefix used in C; linker aliases map to real symbol names */");
    for (const s of absSyms) {
      lines.push(`extern ${s.cType} _far_${s.name}[12];`);
      lines.push(`#define ${s.name} (*((${s.cType}*)_far_${s.name}))`);
    }
    lines.push("");
  }

  lines.push("#endif");
  lines.push("");

  return lines.join("\n");
}

/** Plain extern declarations for m2c --context (no macros, no arrays) */
function generateM2cContext(symbols: SymbolInfo[]): string {
  const lines: string[] = [
    "/* Generated by tools/classifyGlobals.ts — m2c context file */",
    "/* Plain externs so m2c knows these symbols exist and won't re-declare them */",
    "",
  ];
  for (const s of symbols) {
    lines.push(`extern ${s.cType} ${s.name};`);
  }
  lines.push("");
  return lines.join("\n");
}

function generateLinkerAliases(symbols: SymbolInfo[]): string {
  const absSyms = symbols.filter(s => !s.inGpRange);
  const lines: string[] = [
    "/* Generated by tools/classifyGlobals.ts — do not edit manually */",
    "/* Maps _far_D_XXXX symbols (used in C for absolute addressing) to real addresses */",
    "",
  ];

  for (const s of absSyms) {
    lines.push(`_far_${s.name} = ${s.name};`);
  }
  lines.push("");

  return lines.join("\n");
}

// --- Main ---

const gpValue = readGpValue();
console.log(`GP value: ${gpValue.toString(16)}`);
console.log(`GP range: ${(gpValue - 0x7ff0).toString(16)} — ${(gpValue + 0x7fef).toString(16)}`);

const symbols = readSymbols(gpValue);
console.log(`Data symbols: ${symbols.length} total`);
console.log(`  In GP range:  ${symbols.filter(s => s.inGpRange).length}`);
console.log(`  Outside GP:   ${symbols.filter(s => !s.inGpRange).length}`);

inferTypes(symbols);

const header = generateHeader(symbols);
const linkerAliases = generateLinkerAliases(symbols);
const m2cContext = generateM2cContext(symbols);

if (writeMode) {
  const headerPath = join(ROOT, "include/globals.h");
  writeFileSync(headerPath, header);
  console.log(`Wrote ${headerPath}`);

  const aliasPath = join(ROOT, "build/globals_aliases.txt");
  writeFileSync(aliasPath, linkerAliases);
  console.log(`Wrote ${aliasPath}`);

  const m2cPath = join(ROOT, "build/m2c_globals.ctx");
  writeFileSync(m2cPath, m2cContext);
  console.log(`Wrote ${m2cPath}`);
} else {
  console.log("\n--- include/globals.h (dry run) ---\n");
  console.log(header);
  console.log("\n--- build/globals_aliases.txt (dry run) ---\n");
  console.log(linkerAliases);
  console.log("Run with --write to save.");
}
