/**
 * contextExport.ts — Extract function signatures from decompiled C files into include/functions.h
 *
 * Stage 4 of the decompilation pipeline. After a function is byte-matched and cleaned up,
 * this tool extracts its signature and adds it to include/functions.h so that future
 * m2c runs and LLM agents have type context.
 *
 * Usage:
 *   npx tsx tools/contextExport.ts func_80011F08          # extract from src/func_80011F08.c
 *   npx tsx tools/contextExport.ts --all                   # extract from all decompiled src/*.c
 *   npx tsx tools/contextExport.ts func_80011F08 --dry-run # show what would be added
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from "fs";
import { join } from "path";

const ROOT = new URL("..", import.meta.url).pathname;

// Match a C function definition: return type, name, params, opening brace
// Handles pointer return types (int *), multi-word types (unsigned int), etc.
const FUNC_DEF_RE = /^([\w][\w\s]*\*?)\s+([\w]+)\s*\(([^)]*)\)\s*\{/gm;

// Lines that are not function definitions
const SKIP_RE = /^(?:#include|\/\/|\/\*|\*|$)/;

interface ExportResult {
  signatures: string[];
  skipped: boolean;
  reason?: string;
}

/**
 * Extract function signatures from a decompiled C file.
 */
export function extractSignatures(cFilePath: string): string[] {
  if (!existsSync(cFilePath)) return [];

  const source = readFileSync(cFilePath, "utf-8");

  // Skip stubs that still use INCLUDE_ASM
  if (source.includes("INCLUDE_ASM(")) return [];

  const signatures: string[] = [];
  let match: RegExpExecArray | null;

  // Reset regex state
  FUNC_DEF_RE.lastIndex = 0;

  while ((match = FUNC_DEF_RE.exec(source)) !== null) {
    const returnType = match[1].trim();
    const funcName = match[2];
    const params = match[3].trim();

    // Normalize empty params to void
    const normalizedParams = params === "" ? "void" : params;
    signatures.push(`${returnType} ${funcName}(${normalizedParams});`);
  }

  return signatures;
}

/**
 * Read the current include/functions.h and return a map of funcName -> signature line.
 */
function readExistingHeader(headerPath: string): Map<string, string> {
  const map = new Map<string, string>();
  if (!existsSync(headerPath)) return map;

  const content = readFileSync(headerPath, "utf-8");
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    // Match signature lines: "type funcname(...);"
    const m = trimmed.match(/^[\w][\w\s]*\*?\s+([\w]+)\s*\(/);
    if (m) {
      map.set(m[1], trimmed);
    }
  }
  return map;
}

/**
 * Write include/functions.h with sorted signatures.
 */
function writeHeader(headerPath: string, signatures: Map<string, string>): void {
  // Sort by function name (which sorts by address for func_XXXXXXXX names)
  const sorted = [...signatures.entries()].sort((a, b) => a[0].localeCompare(b[0]));

  // No preprocessor directives — m2c parses this as plain C context
  const lines = [
    "/* Auto-generated by tools/contextExport.ts — do not edit manually */",
    "",
    "typedef unsigned char u8;",
    "typedef unsigned short u16;",
    "typedef unsigned int u32;",
    "typedef signed char s8;",
    "typedef signed short s16;",
    "typedef signed int s32;",
    "",
    ...sorted.map(([_, sig]) => sig),
    "",
  ];

  writeFileSync(headerPath, lines.join("\n"));
}

/**
 * Export context for a single function. Returns extracted signatures.
 * This is the entry point used by the orchestrator.
 */
export function exportContext(funcName: string, rootDir: string = ROOT): ExportResult {
  const cFile = join(rootDir, "src", `${funcName}.c`);

  if (!existsSync(cFile)) {
    return { signatures: [], skipped: true, reason: "file not found" };
  }

  const sigs = extractSignatures(cFile);
  if (sigs.length === 0) {
    return { signatures: [], skipped: true, reason: "no function definitions (stub?)" };
  }

  const headerPath = join(rootDir, "include/functions.h");
  const existing = readExistingHeader(headerPath);

  // Merge new signatures into existing
  for (const sig of sigs) {
    const m = sig.match(/^[\w][\w\s]*\*?\s+([\w]+)\s*\(/);
    if (m) {
      existing.set(m[1], sig);
    }
  }

  writeHeader(headerPath, existing);
  return { signatures: sigs, skipped: false };
}

/**
 * Export context for all decompiled (non-stub) C files in src/.
 */
export function exportAll(rootDir: string = ROOT): { exported: string[]; skipped: string[] } {
  const srcDir = join(rootDir, "src");
  if (!existsSync(srcDir)) return { exported: [], skipped: [] };

  const files = readdirSync(srcDir).filter((f) => f.endsWith(".c"));
  const exported: string[] = [];
  const skipped: string[] = [];

  // Collect all signatures first
  const headerPath = join(rootDir, "include/functions.h");
  const allSigs = readExistingHeader(headerPath);

  for (const file of files) {
    const funcName = file.replace(/\.c$/, "");
    const cFile = join(srcDir, file);
    const sigs = extractSignatures(cFile);

    if (sigs.length === 0) {
      skipped.push(funcName);
      continue;
    }

    for (const sig of sigs) {
      const m = sig.match(/^[\w][\w\s]*\*?\s+([\w]+)\s*\(/);
      if (m) {
        allSigs.set(m[1], sig);
      }
    }
    exported.push(funcName);
  }

  if (exported.length > 0) {
    writeHeader(headerPath, allSigs);
  }

  return { exported, skipped };
}

// --- CLI ---

if (process.argv[1]?.endsWith("contextExport.ts")) {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");
  const all = args.includes("--all");
  const funcName = args.find((a) => !a.startsWith("--"));

  if (!all && !funcName) {
    console.error("Usage: npx tsx tools/contextExport.ts <func_name> [--dry-run]");
    console.error("       npx tsx tools/contextExport.ts --all [--dry-run]");
    process.exit(1);
  }

  if (all) {
    if (dryRun) {
      const srcDir = join(ROOT, "src");
      const files = readdirSync(srcDir).filter((f) => f.endsWith(".c"));
      let count = 0;
      for (const file of files) {
        const sigs = extractSignatures(join(srcDir, file));
        for (const sig of sigs) {
          console.log(sig);
          count++;
        }
      }
      console.log(`\n${count} signature(s) found (dry run, nothing written)`);
    } else {
      const result = exportAll();
      console.log(`Exported ${result.exported.length} function(s), skipped ${result.skipped.length} stub(s)`);
      if (result.exported.length > 0) {
        console.log(`Updated include/functions.h`);
      }
    }
  } else {
    const cFile = join(ROOT, "src", `${funcName}.c`);
    const sigs = extractSignatures(cFile);

    if (sigs.length === 0) {
      console.log(`No function definitions found in src/${funcName}.c (stub or missing)`);
      process.exit(0);
    }

    for (const sig of sigs) {
      console.log(`  ${sig}`);
    }

    if (dryRun) {
      console.log(`(dry run, nothing written)`);
    } else {
      const result = exportContext(funcName!);
      if (!result.skipped) {
        console.log(`Updated include/functions.h`);
      }
    }
  }
}
